### Project specific config ###
environment:
  APM_TEST_PACKAGES:
  ATOM_LINT_WITH_BUNDLED_NODE: "true"
  CI: "true"

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

before_build:
  - git config --global user.email "test@example.com"
  - git config --global user.name "test"

### Generic setup follows ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/uzitech/ci/travis-windows/build-package-travis.ps1'))

branches:
  only:
    - master
    - /^greenkeeper/.*$/

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
